# Generated by Django 3.0.1 on 2020-01-21 13:35

from django.db import migrations, models
import lectures.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('description', models.TextField(default='', verbose_name='description')),
                ('uploadDate', models.DateTimeField(auto_now=True, verbose_name='uploadDate')),
                ('lastModified', models.DateTimeField(auto_now=True, verbose_name='uploadDate')),
                ('publicationDate', models.DateField(verbose_name='publicationDate')),
                ('image', models.ImageField(upload_to=lectures.models.hashImageFilename, verbose_name='image')),
            ],
        ),
    ]
