# Generated by Django 3.0.1 on 2020-01-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='link',
        ),
        migrations.AddField(
            model_name='lecture',
            name='videoID',
            field=models.CharField(default='', max_length=50),
        ),
    ]
