# Generated by Django 3.0.1 on 2020-01-07 13:27

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200107_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to=articles.models.hashImageFilename, verbose_name='image'),
        ),
    ]
