# Generated by Django 3.0.1 on 2020-01-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200107_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='lastModified',
            field=models.DateTimeField(auto_now=True, verbose_name='uploadDate'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publicationDate',
            field=models.DateField(verbose_name='publicationDate'),
        ),
    ]
