# Generated by Django 3.0.1 on 2020-01-21 12:28

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_remove_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=markdownx.models.MarkdownxField(default='', verbose_name='content'),
        ),
    ]
